import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    primary: "#2563EB",
    primaryDark: "#1D4ED8",
    primaryLight: "#EFF6FF",
    bg: "#F8FAFC",
    cardBg: "#FFFFFF",
    border: "#E5E7EB",
    borderSubtle: "#CBD5E1",
    textDark: "#1F2937",
    textMain: "#0F172A",
    textMuted: "#6B7280",
    textSecondary: "#475569",
    success: "#15803D",
    successBg: "#F0FDF4",
    successBorder: "#BBF7D0",
    amber: "#B45309",
    amberBg: "#FFFBEB",
    amberBorder: "#FDE68A",
    danger: "#DC2626",
    dangerBg: "#FEF2F2",
    grayBg: "#F3F4F6",
    grayText: "#4B5563",
  },
  borderRadius: {
    sm: 6,
    md: 8,
    card: 14,
    pill: 999,
  },
  cardShadow: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.bg,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: theme.colors.cardBg,
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 16,
    marginBottom: 16,
    ...theme.cardShadow,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.textMain,
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 13,
    color: theme.colors.textMuted,
    marginBottom: 12,
  },
  btnPrimary: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  btnPrimaryText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  btnOutline: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  btnOutlineText: {
    color: theme.colors.textDark,
    fontSize: 15,
    fontWeight: "600",
  },
  badgeBlue: {
    backgroundColor: theme.colors.primaryLight,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  badgeBlueText: {
    color: theme.colors.primaryDark,
    fontSize: 12,
    fontWeight: "600",
  },
  badgeGreen: {
    backgroundColor: theme.colors.successBg,
    borderWidth: 1,
    borderColor: theme.colors.successBorder,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  badgeGreenText: {
    color: theme.colors.success,
    fontSize: 12,
    fontWeight: "600",
  },
  badgeAmber: {
    backgroundColor: theme.colors.amberBg,
    borderWidth: 1,
    borderColor: theme.colors.amberBorder,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  badgeAmberText: {
    color: theme.colors.amber,
    fontSize: 12,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: theme.colors.textDark,
    marginBottom: 12,
  },
});
